---
title: "Make MIMIC 4"
format: html
editor: visual
---

```{r}
# Load required packages
library(RSQLite)
library(connections)
library(tidyverse)
```

```{bash}
wget -r -N -c -np https://physionet.org/files/mimic-iv-demo/2.2/
```

```{bash}
pip install pandas
```

```{bash}
cat <<EOT > /cloud/project/physionet.org/files/mimic-iv-demo/2.2/import.py
import os
import sqlite3
import sys

from glob import glob
import pandas as pd

DATABASE_NAME = "mimic4.db"
THRESHOLD_SIZE = 5 * 10**7
CHUNKSIZE = 10**6

if os.path.exists(DATABASE_NAME):
    msg = "File {} already exists.".format(DATABASE_NAME)
    print(msg)
    sys.exit()

with sqlite3.Connection(DATABASE_NAME) as connection:
    for f in glob("**/*.csv*", recursive=True):
        print("Starting processing {}".format(f))
        folder, filename = os.path.split(f)
        tablename = filename.lower()
        if tablename.endswith('.gz'):
            tablename = tablename[:-3]
        if tablename.endswith('.csv'):
            tablename = tablename[:-4]
        if os.path.getsize(f) < THRESHOLD_SIZE:
            df = pd.read_csv(f)
            df.to_sql(tablename, connection)
        else:
            # If the file is too large, let's do the work in chunks
            for chunk in pd.read_csv(f, chunksize=CHUNKSIZE, low_memory=False):
                chunk.to_sql(tablename, connection, if_exists="append")
        print("Finished processing {}".format(f))

print("Should be all done!")

EOT
```

```{bash}
python /cloud/project/physionet.org/files/mimic-iv-demo/2.2/import.py
```

```{r}
con4 <- connection_open(RSQLite::SQLite(), "/cloud/project/mimic4.db")
```

```{sql connection=con4}
DROP TABLE IF EXISTS chartevents;
```

```{sql connection=con4}
DROP TABLE IF EXISTS TEMP_DIAGNOSES_ICD;
```


```{sql connection=con4}
-- Step 1: Create a new temporary table with the join
CREATE TABLE TEMP_DIAGNOSES_ICD AS
SELECT di.*, dd.long_title
FROM DIAGNOSES_ICD di
JOIN D_ICD_DIAGNOSES dd ON di.icd_code = dd.icd_code and di.icd_version = dd.icd_version;
```

```{sql connection=con4}
-- Step 2: Drop the original table (make sure you have a backup before doing this!)
DROP TABLE DIAGNOSES_ICD;
```


```{sql connection=con4}
-- Step 3: Rename the temporary table to the original table name
ALTER TABLE TEMP_DIAGNOSES_ICD RENAME TO diagnoses_icd;
```
get rid of fibrin degradation products

```{sql connection=con4}
DELETE FROM D_LABITEMS
WHERE itemid = 51213;
```

remove Phenobarbital
```{sql connection=con4}
DELETE FROM D_LABITEMS
WHERE itemid = 50966;
```



```{sql connection=con4}
VACUUM;
```
